<template>
  <SponsorInvoiceLayout
    title="Daily Report"
    :subtitle="`Finance and end-of-day closeout for ${selectedDateLabel}`"
    :has-error="!!error"
  >
    <template #meta>
      <strong>Report Date:</strong><span>{{ selectedDateLabel }}</span>
      <strong>Branch:</strong><span>{{ formatPrintableName(clinicName, "All branches") }}</span>
      <strong>Generated:</strong><span>{{ generatedAtLabel }}</span>
      <strong>Generated By:</strong><span>{{ formatPrintableName(generatedByLabel, "--") }}</span>
    </template>

    <template #toolbar>
      <Button label="Print" icon="pi pi-print" @click="printPage('landscape')" />
      <Button label="Close" icon="pi pi-times" severity="secondary" outlined @click="goBack" />
    </template>

    <template v-if="error" #error>
      {{ error }}
    </template>



    <template v-if="!error">
      <section class="daily-report-section">
        <h2 class="daily-report-section-title">Finance Summary</h2>
        <div class="daily-report-metrics">
          <div v-for="metric in financeMetrics" :key="metric.label" class="daily-report-metric">
            <div class="daily-report-metric__label">{{ metric.label }}</div>
            <div class="daily-report-metric__value">{{ metric.value }}</div>
          </div>
        </div>
      </section>



      <!-- <section class="daily-report-section">
        <h2 class="daily-report-section-title">Completed Patients</h2>
        <div class="table-wrap">
          <table class="summary-table daily-report-table completed-patients-table">
            <thead>
              <tr>
                <th class="text-left">Time</th>
                <th class="text-left">Patient</th>
                <th class="text-left">Primary PT</th>
                <th class="text-left">Payer</th>
                <th class="text-left">Billing Record</th>
                <th class="text-right">Tendered Today</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="!completedAppointments.length">
                <td colspan="6" class="empty-row">No completed patients recorded for this date.</td>
              </tr>
              <tr v-for="row in completedAppointments" :key="row.id">
                <td>{{ formatTime(row.starts_at) }}</td>
                <td>
                  <strong>{{ formatPrintableName(row.patient_name, "Unnamed patient") }}</strong>
                  <span>{{ row.patient_public_id }}</span>
                </td>
                <td>{{ formatPrintableName(row.pt_name, "Unassigned PT") }}</td>
                <td>{{ formatPayerType(row.payer_type) }}</td>
                <td>
                  {{ row.billing_number || "--" }}
                  <span>{{ row.billing_status || "No billing record" }}{{ row.billing_document_date ? ` / ${row.billing_document_date}` : "" }}</span>
                </td>
                <td class="text-right">{{ asCurrency(row.amount_paid) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section> -->

      <section class="daily-report-section">
        <h2 class="daily-report-section-title">Daily Income</h2>
        <div class="table-wrap">
          <table class="summary-table daily-report-table income-table">
            <thead>
              <tr>
                <th class="text-center report-number-column">No.</th>
                <th class="text-left">Patient</th>
                <th class="text-left">Billing Record ID</th>
                <th class="text-left">Billing Type</th>
                <th class="text-right">Price</th>
                <th class="text-right">Tendered Today</th>
                <th class="text-left">Mode of Payment</th>
                <th class="text-right">Balance</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="!incomes.length">
                <td colspan="8" class="empty-row">No billing activity recorded for this date.</td>
              </tr>
              <tr v-for="(row, index) in incomes" :key="row.id">
                <td class="text-center report-number-column">{{ index + 1 }}</td>
                <td>
                  <strong>{{ formatPrintableName(row.patient_name, "Unnamed patient") }}</strong>
                </td>
                <td>
                  {{ getBillingRecordId(row) }}
                  <span>{{ formatTime(row.created_at) }}</span>
                </td>
                <td>{{ row.billing_route }}</td>
                <td class="text-right">{{ asCurrency(row.payment_amount) }}</td>
                <td class="text-right">{{ asCurrency(row.tendered_today ?? row.collected_amount) }}</td>
                <td>{{ row.mode_of_payment || "--" }}</td>
                <td class="text-right">{{ asCurrency(row.balance) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section class="daily-report-section">
        <h2 class="daily-report-section-title">Expenses</h2>
        <div class="table-wrap">
          <table class="summary-table daily-report-table">
            <thead>
              <tr>
                <th class="text-center report-number-column">No.</th>
                <th class="text-left">Item</th>
                <th class="text-right">Amount</th>
                <th class="text-left">Created By</th>
                <th class="text-left">Created At</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="!expenses.length">
                <td colspan="5" class="empty-row">No expense entries recorded for this date.</td>
              </tr>
              <tr v-for="(row, index) in expenses" :key="row.id">
                <td class="text-center report-number-column">{{ index + 1 }}</td>
                <td>
                  <strong>{{ row.item_name }}</strong>
                  <span v-if="row.notes" style="font-size: 10px; text-transform: capitalize;">notes: {{ row.notes }}</span>
                </td>
                <td class="text-right">{{ asCurrency(row.amount) }}</td>
                <td>{{ formatPrintableName(row.created_by_name, "--") }}</td>
                <td>{{ formatDateTime(row.created_at) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section class="daily-report-section">
        <h2 class="daily-report-section-title">Daily Totals</h2>
        <div class="daily-report-metrics daily-report-metrics--totals">
          <div class="daily-report-metric">
            <div class="daily-report-metric__label">Gross Charge</div>
            <div class="daily-report-metric__value">{{ asCurrency(summary.gross_income) }}</div>
          </div>
          <div class="daily-report-metric">
            <div class="daily-report-metric__label">Outstanding</div>
            <div class="daily-report-metric__value">{{ asCurrency(summary.outstanding_balance) }}</div>
          </div>
          <div class="daily-report-metric">
            <div class="daily-report-metric__label">Net Cash</div>
            <div class="daily-report-metric__value">{{ asCurrency(summary.net_cash) }}</div>
          </div>
          <div class="daily-report-metric">
            <div class="daily-report-metric__label">Expense Total</div>
            <div class="daily-report-metric__value">{{ asCurrency(summary.expense_total) }}</div>
          </div>
        </div>
      </section>
    </template>

    <template v-if="!error" #bottom>
      <section class="daily-report-signatures" style="margin-top: 40px;">
        <div class="daily-report-signature">Prepared By</div>
        <div class="daily-report-signature">Reviewed By</div>
        <div class="daily-report-signature">Approved By</div>
      </section>
    </template>
  </SponsorInvoiceLayout>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { useRoute } from "vue-router"
import Button from "primevue/button"
import {
  appointmentPhase1Service,
  type PtEndOfDayReport
} from "@/features/appointments/api/appointment-phase1.service"
import {
  billingPhase1Service,
  type DailyExpenseEntry,
  type DailyIncomeExpenseReport,
  type DailyIncomeExpenseRow
} from "@/features/billing/api/billing-phase1.service"
import SponsorInvoiceLayout from "@/features/shared/invoices/SponsorInvoiceLayout.vue"
import { useSponsorInvoicePrintActions } from "@/features/shared/invoices/sponsor-invoice.shared"
import { useAuthSessionStore } from "@/stores/auth-session.store"

type PendingPtRow = {
  pt_name: string
  pending_pt_signature_count: number
  eligible_appointment_count: number
}

type PendingEodBlocker = NonNullable<PtEndOfDayReport["pending_eod_blockers"]>[number]

type Metric = {
  label: string
  value: string
}

const route = useRoute()
const authSession = useAuthSessionStore()
const { printPage, goBack } = useSponsorInvoicePrintActions()

const report = ref<DailyIncomeExpenseReport>()
const eodReport = ref<PtEndOfDayReport>()
const error = ref("")
const generatedAt = ref(new Date())

const selectedDate = computed(() => parseDateQuery(route.query.date) || toDateParam(new Date()))
const clinicId = computed(() => parsePositiveNumber(route.query.clinic_id))
const queryClinicName = computed(() => String(route.query.clinic_name ?? "").trim())

const selectedDateLabel = computed(() =>
  new Date(`${selectedDate.value}T00:00:00`).toLocaleDateString("en-PH", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric"
  })
)

const generatedAtLabel = computed(() => formatDateTime(generatedAt.value.toISOString()))
const generatedByLabel = computed(() => authSession.staffName || "--")

const formatPrintableName = (value?: string | null, fallback = "N/A"): string => {
  const name = String(value ?? "").trim()
  return name ? name.toUpperCase() : fallback
}

const clinicName = computed(() =>
  eodReport.value?.clinic?.name ||
  queryClinicName.value ||
  "All branches"
)

const eodWindowLabel = computed(() => {
  const clinic = eodReport.value?.clinic
  if (!clinic) return "No branch EOD window loaded."
  return `${clinic.name} window: ${formatDateTime(clinic.window_starts_at)} to ${formatDateTime(clinic.window_ends_at)}`
})

const summary = computed(() => report.value?.summary ?? {
  income_entry_count: 0,
  expense_entry_count: 0,
  unbilled_appointment_count: 0,
  incomplete_billing_count: 0,
  partial_billing_count: 0,
  gross_income: 0,
  cash_collected: 0,
  tendered_today_total: 0,
  tendered_cash: 0,
  tendered_ewallet: 0,
  tendered_debit_credit: 0,
  tendered_other: 0,
  outstanding_balance: 0,
  incomplete_billing_balance: 0,
  expense_total: 0,
  net_cash: 0
})

const incomes = computed<DailyIncomeExpenseRow[]>(() => report.value?.incomes ?? [])
const completedAppointments = computed(() => report.value?.completed_appointments ?? [])
const expenses = computed<DailyExpenseEntry[]>(() => report.value?.expenses ?? [])
const pendingEodBlockers = computed<PendingEodBlocker[]>(() => eodReport.value?.pending_eod_blockers ?? [])

const outstandingByRoute = computed(() => incomes.value.reduce(
  (totals, row) => {
    const route = row.billing_route?.trim().toUpperCase()
    if (route === "HMO") totals.hmo += numberValue(row.balance)
    else if (route === "LGU") totals.lgu += numberValue(row.balance)
    else totals.selfPay += numberValue(row.balance)
    return totals
  },
  { selfPay: 0, hmo: 0, lgu: 0 }
))

const pendingPtRows = computed<PendingPtRow[]>(() =>
  (eodReport.value?.pending_pt_signatures_by_pt ?? []).map((row) => ({
    pt_name: String(row.pt_name ?? "Unassigned PT"),
    pending_pt_signature_count: numberValue(row.pending_pt_signature_count),
    eligible_appointment_count: numberValue(row.eligible_appointment_count)
  }))
)

const financeMetrics = computed<Metric[]>(() => [
  { label: "Gross Charges", value: asCurrency(summary.value.gross_income) },
  { label: "Cash", value: asCurrency(summary.value.tendered_cash) },
  { label: "E-wallets", value: asCurrency(summary.value.tendered_ewallet) },
  { label: "Debit/Credit", value: asCurrency(summary.value.tendered_debit_credit) },
  { label: "Self-Pay Outstanding", value: asCurrency(outstandingByRoute.value.selfPay) },
  { label: "HMO Outstanding", value: asCurrency(outstandingByRoute.value.hmo) },
  { label: "LGU Outstanding", value: asCurrency(outstandingByRoute.value.lgu) },
  { label: "Expenses", value: asCurrency(summary.value.expense_total) },
  { label: "Net Cash", value: asCurrency(summary.value.net_cash) }
])

const eodMetrics = computed<Metric[]>(() => {
  const eodSummary = eodReport.value?.summary
  return [
    { label: "EOD Status", value: getEodStatusLabel(eodReport.value) },
    { label: "Pending Appointments", value: String(eodSummary?.pending_appointment_count ?? 0) },
    { label: "Pending PT Signatures", value: String(eodSummary?.pending_pt_signature_count ?? 0) },
    {
      label: "Billing Cleared",
      value: `${eodSummary?.billing_cleared_appointments ?? 0}/${eodSummary?.eligible_appointments ?? 0}`
    },
    { label: "Eligible Appts", value: String(eodSummary?.eligible_appointments ?? 0) }
  ]
})

const asCurrency = (value: number): string =>
  new Intl.NumberFormat("en-PH", {
    style: "currency",
    currency: "PHP",
    maximumFractionDigits: 2
  }).format(Number(value ?? 0))

const numberValue = (value: unknown): number => Number(value ?? 0)

const toDateParam = (value: Date): string => {
  const year = value.getFullYear()
  const month = String(value.getMonth() + 1).padStart(2, "0")
  const day = String(value.getDate()).padStart(2, "0")
  return `${year}-${month}-${day}`
}

const parseDateQuery = (value: unknown): string | null => {
  const raw = String(value ?? "").trim()
  return /^\d{4}-\d{2}-\d{2}$/.test(raw) ? raw : null
}

const parsePositiveNumber = (value: unknown): number | undefined => {
  const numeric = Number(value)
  return Number.isFinite(numeric) && numeric > 0 ? numeric : undefined
}

const formatTime = (value?: string | null): string => {
  if (!value) return "--"
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return "--"
  return date.toLocaleTimeString("en-PH", {
    hour: "numeric",
    minute: "2-digit"
  })
}

const formatDateTime = (value?: string | null): string => {
  if (!value) return "--"
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return "--"
  return date.toLocaleString("en-PH", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit"
  })
}

const getBillingRecordId = (row: { id: number; public_id?: string | null }): string =>
  row.public_id?.trim() || `BILLING-${row.id}`

const formatPayerType = (value?: string | null): string => {
  const normalized = String(value ?? "").trim().toUpperCase()
  if (normalized === "SELF_PAY_SINGLE") return "Self-Pay"
  if (normalized === "SELF_PAY_PACKAGE") return "Self-Pay Package"
  if (normalized === "HMO") return "HMO"
  if (normalized === "LGU") return "LGU"
  return normalized || "--"
}

const getEodStatusLabel = (current?: PtEndOfDayReport): string => {
  const eodSummary = current?.summary
  if (!eodSummary) return "Waiting for report data"
  if (current?.eod_report_generated) return "Generated"
  if (eodSummary.pending_appointment_count > 0) return "Waiting for pending appointments"
  if (eodSummary.pending_pt_signature_count > 0) return "Waiting for PT signatures"
  if (eodSummary.pending_billing_count > 0) return "Waiting for billing clearance"
  if (!eodSummary.eligible_appointments) return "No active appointments"
  return "Waiting"
}

onMounted(async () => {
  try {
    await authSession.ensureLoaded()
  } catch {
    // Keep printable usable even if staff display name is unavailable.
  }

  try {
    const [dailyResult, eodResult] = await Promise.allSettled([
      billingPhase1Service.getDailyIncomeExpense(selectedDate.value, clinicId.value),
      clinicId.value
        ? appointmentPhase1Service.getPtEndOfDay(selectedDate.value, clinicId.value)
        : Promise.resolve(undefined)
    ])

    if (dailyResult.status === "fulfilled") report.value = dailyResult.value
    else throw dailyResult.reason

    if (eodResult.status === "fulfilled") eodReport.value = eodResult.value
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : "Daily report could not be loaded."
  }
})
</script>

<style scoped>
.daily-report-details {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 8px 10px;
}

.daily-report-details__group {
  display: grid;
  gap: 4px;
}

.daily-report-line {
  display: grid;
  grid-template-columns: 120px minmax(0, 1fr);
  gap: 8px;
  font-size: 11px;
}

.daily-report-label {
  font-weight: 800;
  color: #111827;
}

.daily-report-value {
  min-width: 0;
  overflow-wrap: anywhere;
}

.daily-report-section {
  margin-top: 12px;
}

.daily-report-section-title {
  margin: 0 0 6px;
  border-bottom: 2px solid #d31d6e;
  padding-bottom: 3px;
  color: #111827;
  font-size: 13px;
  font-weight: 800;
  text-transform: uppercase;
}

.daily-report-subtitle {
  margin-bottom: 6px;
  color: #374151;
  font-size: 10px;
}

.daily-report-metrics {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 6px;
}

.daily-report-metrics--eod,
.daily-report-metrics--totals {
  grid-template-columns: repeat(5, minmax(0, 1fr));
}

.daily-report-metrics--totals {
  grid-template-columns: repeat(5, minmax(0, 1fr));
}

.daily-report-metric {
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 6px 8px;
  background: #f8fafc;
}

.daily-report-metric__label {
  color: #6b7280;
  font-size: 9px;
  font-weight: 800;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.daily-report-metric__value {
  margin-top: 2px;
  color: #111827;
  font-size: 12px;
  font-weight: 800;
}

.daily-report-table {
  font-size: 9px;
  table-layout: fixed;
}

.daily-report-table th,
.daily-report-table td {
  padding: 4px 5px;
  vertical-align: top;
  overflow-wrap: anywhere;
}

.daily-report-table td span {
  display: block;
  color: #6b7280;
  font-size: 8px;
}

.report-number-column {
  width: 24px !important;
  min-width: 24px !important;
  max-width: 24px !important;
  padding-left: 2px !important;
  padding-right: 2px !important;
  white-space: nowrap;
}

.daily-report-signatures {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 18px;
  width: 100%;
}

.daily-report-signature {
  margin-top: 28px;
  border-top: 1px solid #111827;
  padding-top: 4px;
  text-align: center;
  font-size: 10px;
  font-weight: 700;
}

@media print {
  .daily-report-section {
    break-inside: avoid;
    page-break-inside: avoid;
    margin-top: 8px;
  }

  .daily-report-details {
    padding: 5px 7px !important;
  }

  .daily-report-line {
    font-size: 9px !important;
    line-height: 1.2 !important;
  }

  .daily-report-section-title {
    margin-bottom: 4px !important;
    font-size: 10px !important;
  }

  .daily-report-metrics {
    gap: 4px !important;
  }

  .daily-report-metric {
    padding: 4px 5px !important;
  }

  .daily-report-metric__label {
    font-size: 7px !important;
  }

  .daily-report-metric__value {
    font-size: 9px !important;
  }

  .daily-report-table {
    font-size: 7px !important;
  }

  .daily-report-table th,
  .daily-report-table td {
    padding: 2px 3px !important;
    line-height: 1.12 !important;
  }

  .daily-report-table td span {
    font-size: 6.5px !important;
  }

  .report-number-column {
    width: 18px !important;
    min-width: 18px !important;
    max-width: 18px !important;
    padding-left: 1px !important;
    padding-right: 1px !important;
  }
}
</style>
