<template>
  <SponsorInvoiceLayout
    title="Monthly Report"
    :subtitle="`Finance monthly rollup for ${selectedMonthLabel}`"
    :has-error="!!error"
  >
    <template #meta>
      <strong>Report Month:</strong><span>{{ selectedMonthLabel }}</span>
      <strong>Branch:</strong><span>{{ formatPrintableName(clinicName, "All branches") }}</span>
      <strong>Generated:</strong><span>{{ generatedAtLabel }}</span>
      <strong>Generated By:</strong><span>{{ formatPrintableName(generatedByLabel, "--") }}</span>
    </template>

    <template #toolbar>
      <Button label="Print" icon="pi pi-print" @click="printPage('landscape')" />
      <Button label="Close" icon="pi pi-times" severity="secondary" outlined @click="goBack" />
    </template>

    <template v-if="error" #error>
      {{ error }}
    </template>

    <template v-if="!error">
      <section class="monthly-report-section">
        <h2 class="monthly-report-section-title">Finance Summary</h2>
        <div class="monthly-report-metrics">
          <div v-for="metric in financeMetrics" :key="metric.label" class="monthly-report-metric">
            <div class="monthly-report-metric__label">{{ metric.label }}</div>
            <div class="monthly-report-metric__value">{{ metric.value }}</div>
          </div>
        </div>
      </section>

      <section class="monthly-report-section">
        <h2 class="monthly-report-section-title">Daily Rollup</h2>
        <div class="table-wrap">
          <table class="summary-table monthly-report-table">
            <thead>
              <tr>
                <th class="text-center report-number-column">No.</th>
                <th class="text-left">Date</th>
                <th class="text-right">Income Rows</th>
                <th class="text-right">Expense Rows</th>
                <th class="text-right">Gross</th>
                <th class="text-right">Outstanding</th>
                <th class="text-right">Expenses</th>
                <th class="text-right">Net Cash</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="!days.length">
                <td colspan="8" class="empty-row">No finance activity found for this month.</td>
              </tr>
              <tr v-for="(row, index) in days" :key="row.report_date">
                <td class="text-center report-number-column">{{ index + 1 }}</td>
                <td>{{ formatMonthDay(row.report_date) }}</td>
                <td class="text-right">{{ row.income_entry_count }}</td>
                <td class="text-right">{{ row.expense_entry_count }}</td>
                <td class="text-right">{{ asCurrency(row.gross_income) }}</td>
                <td class="text-right">{{ asCurrency(row.outstanding_balance) }}</td>
                <td class="text-right">{{ asCurrency(row.expense_total) }}</td>
                <td class="text-right">{{ asCurrency(row.net_cash) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section class="monthly-report-section">
        <h2 class="monthly-report-section-title">Monthly Totals</h2>
        <div class="monthly-report-metrics monthly-report-metrics--totals">
          <div class="monthly-report-metric">
            <div class="monthly-report-metric__label">Gross Charge</div>
            <div class="monthly-report-metric__value">{{ asCurrency(summary.gross_income) }}</div>
          </div>
          <div class="monthly-report-metric">
            <div class="monthly-report-metric__label">Expenses</div>
            <div class="monthly-report-metric__value">{{ asCurrency(summary.expense_total) }}</div>
          </div>
          <div class="monthly-report-metric">
            <div class="monthly-report-metric__label">Net Cash</div>
            <div class="monthly-report-metric__value">{{ asCurrency(summary.net_cash) }}</div>
          </div>
        </div>
      </section>
    </template>

    <template v-if="!error" #bottom>
      <section class="monthly-report-signatures">
        <div class="monthly-report-signature">Prepared By</div>
        <div class="monthly-report-signature">Reviewed By</div>
        <div class="monthly-report-signature">Approved By</div>
      </section>
    </template>
  </SponsorInvoiceLayout>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { useRoute } from "vue-router"
import Button from "primevue/button"
import {
  billingPhase1Service,
  type MonthlyIncomeExpenseDay,
  type MonthlyIncomeExpenseReport
} from "@/features/billing/api/billing-phase1.service"
import SponsorInvoiceLayout from "@/features/shared/invoices/SponsorInvoiceLayout.vue"
import { useSponsorInvoicePrintActions } from "@/features/shared/invoices/sponsor-invoice.shared"
import { useAuthSessionStore } from "@/stores/auth-session.store"

type Metric = {
  label: string
  value: string
}

const route = useRoute()
const authSession = useAuthSessionStore()
const { printPage, goBack } = useSponsorInvoicePrintActions()

const report = ref<MonthlyIncomeExpenseReport>()
const error = ref("")
const generatedAt = ref(new Date())

const selectedMonth = computed(() => parseMonthQuery(route.query.month) || toMonthParam(new Date()))
const selectedDate = computed(() => parseDateQuery(route.query.date) || `${selectedMonth.value}-01`)
const clinicId = computed(() => parsePositiveNumber(route.query.clinic_id))
const queryClinicName = computed(() => String(route.query.clinic_name ?? "").trim())

const selectedMonthLabel = computed(() => {
  const [year, month] = selectedMonth.value.split("-").map(Number)
  return new Date(year, month - 1, 1).toLocaleDateString("en-PH", {
    year: "numeric",
    month: "long"
  })
})

const generatedAtLabel = computed(() => formatDateTime(generatedAt.value.toISOString()))
const generatedByLabel = computed(() => authSession.staffName || "--")
const clinicName = computed(() => queryClinicName.value || "All branches")

const emptySummary = {
  active_day_count: 0,
  days_with_income: 0,
  days_with_expenses: 0,
  income_entry_count: 0,
  expense_entry_count: 0,
  unbilled_appointment_count: 0,
  incomplete_billing_count: 0,
  partial_billing_count: 0,
  gross_income: 0,
  cash_collected: 0,
  tendered_cash: 0,
  tendered_ewallet: 0,
  tendered_debit_credit: 0,
  tendered_other: 0,
  outstanding_balance: 0,
  incomplete_billing_balance: 0,
  expense_total: 0,
  net_cash: 0
}

const summary = computed(() => report.value?.summary ?? emptySummary)
const days = computed<MonthlyIncomeExpenseDay[]>(() => report.value?.days ?? [])

const financeMetrics = computed<Metric[]>(() => [
  { label: "Gross Charges", value: asCurrency(summary.value.gross_income) },
  { label: "Cash", value: asCurrency(summary.value.tendered_cash) },
  { label: "E-wallets", value: asCurrency(summary.value.tendered_ewallet) },
  { label: "Debit/Credit", value: asCurrency(summary.value.tendered_debit_credit) },
  { label: "Outstanding", value: asCurrency(summary.value.outstanding_balance) },
  { label: "Incomplete Billings", value: `${summary.value.incomplete_billing_count} / ${asCurrency(summary.value.incomplete_billing_balance)}` },
  { label: "Expenses", value: asCurrency(summary.value.expense_total) },
  { label: "Net Cash", value: asCurrency(summary.value.net_cash) },
  { label: "Active Days", value: String(summary.value.active_day_count) }
])

const formatPrintableName = (value?: string | null, fallback = "N/A"): string => {
  const name = String(value ?? "").trim()
  return name ? name.toUpperCase() : fallback
}

const asCurrency = (value: number): string =>
  new Intl.NumberFormat("en-PH", {
    style: "currency",
    currency: "PHP",
    maximumFractionDigits: 2
  }).format(Number(value ?? 0))

const toMonthParam = (value: Date): string => {
  const year = value.getFullYear()
  const month = String(value.getMonth() + 1).padStart(2, "0")
  return `${year}-${month}`
}

const parseMonthQuery = (value: unknown): string | null => {
  const raw = String(value ?? "").trim()
  return /^\d{4}-\d{2}$/.test(raw) ? raw : null
}

const parseDateQuery = (value: unknown): string | null => {
  const raw = String(value ?? "").trim()
  return /^\d{4}-\d{2}-\d{2}$/.test(raw) ? raw : null
}

const parsePositiveNumber = (value: unknown): number | undefined => {
  const numeric = Number(value)
  return Number.isFinite(numeric) && numeric > 0 ? numeric : undefined
}

const formatMonthDay = (value: string): string =>
  new Date(`${value}T00:00:00`).toLocaleDateString("en-PH", {
    month: "short",
    day: "numeric",
    weekday: "short"
  })

const formatDateTime = (value?: string | null): string => {
  if (!value) return "--"
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return "--"
  return date.toLocaleString("en-PH", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit"
  })
}

onMounted(async () => {
  try {
    await authSession.ensureLoaded()
  } catch {
    error.value = "Monthly report could not verify the signed-in user."
    return
  }

  if (!authSession.isOwnerEquivalent) {
    error.value = "Monthly report is available only to owner-level users."
    return
  }

  try {
    report.value = await billingPhase1Service.getMonthlyIncomeExpense(
      selectedMonth.value,
      selectedDate.value,
      clinicId.value
    )
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : "Monthly report could not be loaded."
  }
})
</script>

<style scoped>
.monthly-report-section {
  margin-top: 12px;
}

.monthly-report-section-title {
  margin: 0 0 6px;
  border-bottom: 2px solid #d31d6e;
  padding-bottom: 3px;
  color: #111827;
  font-size: 13px;
  font-weight: 800;
  text-transform: uppercase;
}

.monthly-report-metrics {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 6px;
}

.monthly-report-metrics--totals {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.monthly-report-metric {
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 6px 8px;
  background: #f8fafc;
}

.monthly-report-metric__label {
  color: #6b7280;
  font-size: 9px;
  font-weight: 800;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.monthly-report-metric__value {
  margin-top: 2px;
  color: #111827;
  font-size: 12px;
  font-weight: 800;
}

.monthly-report-table {
  font-size: 9px;
  table-layout: fixed;
}

.monthly-report-table th,
.monthly-report-table td {
  padding: 4px 5px;
  vertical-align: top;
  overflow-wrap: anywhere;
}

.report-number-column {
  width: 24px !important;
  min-width: 24px !important;
  max-width: 24px !important;
  padding-left: 2px !important;
  padding-right: 2px !important;
  white-space: nowrap;
}

.monthly-report-signatures {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 18px;
  width: 100%;
}

.monthly-report-signature {
  margin-top: 28px;
  border-top: 1px solid #111827;
  padding-top: 4px;
  text-align: center;
  font-size: 10px;
  font-weight: 700;
}

@media print {
  .monthly-report-section {
    break-inside: avoid;
    page-break-inside: avoid;
    margin-top: 8px;
  }

  .monthly-report-section-title {
    margin-bottom: 4px !important;
    font-size: 10px !important;
  }

  .monthly-report-metrics {
    gap: 4px !important;
  }

  .monthly-report-metric {
    padding: 4px 5px !important;
  }

  .monthly-report-metric__label {
    font-size: 7px !important;
  }

  .monthly-report-metric__value {
    font-size: 9px !important;
  }

  .monthly-report-table {
    font-size: 7px !important;
  }

  .monthly-report-table th,
  .monthly-report-table td {
    padding: 2px 3px !important;
    line-height: 1.12 !important;
  }

  .report-number-column {
    width: 18px !important;
    min-width: 18px !important;
    max-width: 18px !important;
    padding-left: 1px !important;
    padding-right: 1px !important;
  }
}
</style>
